"""
core/image_processor.py — Post-processing utilities for generated designs.

Background removal is currently disabled. Designs are saved as white-background
PNGs exactly as generated by gpt-image-1.

When we add coloured or black mug products to Printify we can revisit this with
a simple white-threshold approach suited to flat vector art rather than the
neural-network rembg approach (which is designed for photos).
"""

from __future__ import annotations


def process_design_background(
    image_path: str,
    threshold: int = 40,
) -> str:
    """
    No-op. Background removal is disabled.

    Returns image_path unchanged so all call sites keep working without
    modification when this step is re-enabled.
    """
    print("[image_processor] Background removal is disabled — returning image unchanged")
    return image_path


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python core/image_processor.py <image.png>")
        sys.exit(1)

    out = process_design_background(sys.argv[1])
    print(f"No-op: {out}")
